# Generated by Django 3.2.4 on 2021-07-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activite', models.TextField(unique=True)),
                ('besoins', models.TextField(default='[]')),
            ],
            options={
                'db_table': 'Activite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id_espace', models.AutoField(primary_key=True, serialize=False)),
                ('lundi_matin', models.TextField(blank=True, default='[]', null=True)),
                ('lundi_aprem', models.TextField(blank=True, default='[]', null=True)),
                ('mardi_matin', models.TextField(blank=True, default='[]', null=True)),
                ('mardi_aprem', models.TextField(blank=True, default='[]', null=True)),
                ('mercredi_matin', models.TextField(blank=True, default='[]', null=True)),
                ('mercredi_aprem', models.TextField(blank=True, default='[]', null=True)),
                ('jeudi_matin', models.TextField(blank=True, default='[]', null=True)),
                ('jeudi_aprem', models.TextField(blank=True, default='[]', null=True)),
                ('vendredi_matin', models.TextField(blank=True, default='[]', null=True)),
                ('vendredi_aprem', models.TextField(blank=True, default='[]', null=True)),
            ],
            options={
                'db_table': 'Agenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Espace',
            fields=[
                ('id_espace', models.AutoField(primary_key=True, serialize=False)),
                ('nom_espace', models.TextField()),
                ('acts_ponct', models.TextField(blank=True, default='[]', null=True)),
                ('outils_utilisés', models.TextField(blank=True, default='[]', null=True)),
                ('outils_recommandés', models.TextField(blank=True, default='[]', null=True)),
            ],
            options={
                'db_table': 'Espace',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fonctionnalitebesoin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fonctionnalite', models.TextField()),
                ('besoin', models.TextField()),
            ],
            options={
                'db_table': 'FonctionnaliteBesoin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Outil',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('outil', models.TextField(unique=True)),
                ('categorie', models.TextField()),
                ('fonctionnalites', models.TextField(default='[]')),
            ],
            options={
                'db_table': 'Outil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('admin_bool', models.IntegerField(blank=True, null=True)),
                ('ids_espaces', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Utilisateur',
                'managed': False,
            },
        ),
    ]
